### ISSUE TITLE
Add the trainining operator to the Katib bundle

### ISSUE THREAD

**Issue by grobbie** [canonical/training-operator#24]
The training operator is needed for the Katib bundle to work, so we should add it.

**Comment by ca-scribner** [comment]
I don't think Katib **needs** the training operator to work (katib has other experiment types that work out of the box), but Katib **can use** the training operator.  The training operator is more a plugin that Katib can benefit from.

With that in mind, does it make sense that our default Katib bundle include the training operator?  @DomFleischmann?  I think this is a question that reoccurs in the abstract too - should we include something in the bundle when it **could** be useful, but is not needed?  The same could be said for istio in most of our bundles.  

An alternative could be that we document that training operator is helpful and that it can be added.  Or even have a few bundle files available in github and possibly even in charmstore (one with, one without training operator, etc...)

**Comment by DomFleischmann** [comment]
In general the messaging that I want to have in our platform is not of bundles that come with everything you need but well documented integrations which allow you to build the setup that you want.

In this sense I wouldn't include training operator in the bundle, as katib works without it, but I would like to see clear documentation on how to deploy and training operator with it.

**Comment by DnPlas** [comment]
Agree on having documentation for katib+training operator, though that requires a new issue to clearly defines the goal. I will close this issue and file another one for documentation.
