### ISSUE TITLE
training-operator failed to upgrade 1.6 to 1.7

### ISSUE THREAD

**Issue by i-chvets** [canonical/training-operator#75]
Failed to reach active/idle:

training-operator blocked: K8S resources creation failed

[Jira](https://warthogs.atlassian.net/browse/KF-1105)

Merge into:
- [x] `track/1.6` (release KF v1.7)
- [x] `main`

**Comment by DnPlas** [comment]
Hi @i-chvets, do you mind adding steps to reproduce and some logs? Is this only failing when upgrading or on install?

**Comment by beliaev-maksim** [comment]
also

```
juju refresh training-operator --channel latest/edge --trust
ERROR option provided but not defined: --trust
```

what is the juju version you use?

**Comment by i-chvets** [comment]
Upgrading `training-operator` from `stable` (Rev 6) to `latest/edge` (Rev 135):
```
juju deploy training-operator --channel stable --trust
juju refresh training-operator --channel latest/edge
```

**Comment by i-chvets** [comment]
In KF 1.6 bundle`training-operator` is in `1.5/stable` channel (Rev 65). The proper testing procedure:
```
juju deploy training-operator --channel 1.5/stable --trust
juju refresh training-operator --channel latest/edge
```

**Comment by i-chvets** [comment]
To reproduce using local charm:
- Rebuild `rev93` PodSpec version of `training-operator` and deploy it.
- Build latest sidecar version of `training-operator` and refresh the charm.
- Observe 'Blocked' state.

**Comment by beliaev-maksim** [comment]
@i-chvets it might be that podspec charm configs conflict with those that are pushed by Juju. Maybe during upgrade need to clean them up before installing sidecar ?

**Comment by DnPlas** [comment]
@i-chvets I am confused, these [steps to reproduce](https://github.com/canonical/training-operator/issues/75#issuecomment-1468283158) and the original description of this bug do not match. Could you please confirm what exactly is the issue you are running into and add steps to reproduce?

**Comment by i-chvets** [comment]
> @i-chvets it might be that podspec charm configs conflict with those that are pushed by Juju. Maybe during upgrade need to clean them up before installing sidecar ?

It looks like it is due to order of K8S manifests that are being applied during refresh. In some charms (Seldon, Training Operator) we separated CRD and K8S resources deployment. And in some cases CRD must be installed before other manifests. In other charms CRDs and other manifests are applied in the by the same resource handler that does sorting of the resources before it applies them. So, either we handler order in charm, or we revert to using single K8S handler to do ordering for us.
I am leaning towards putting everything back into single handler.

**Comment by DnPlas** [comment]
> It looks like it is due to order of K8S manifests that are being applied during refresh. In some charms (Seldon, Training Operator) we separated CRD and K8S resources deployment. And in some cases CRD must be installed before other manifests. In other charms CRDs and other manifests are applied in the by the same resource handler that does sorting of the resources before it applies them. To solve the issue, we either handle order in charm, or we revert to using single K8S handler to do ordering for us. I am leaning towards putting everything back into single handler. I need to confirm this first.

@i-chvets before changing anything, we need to understand what is the issue you are running into. Please modify the description of this issue with logs, error messages and steps to reproduce. You have referenced two different error messages and two different set of steps to reproduce, and that makes it hard to understand.

**Comment by i-chvets** [comment]
> > It looks like it is due to order of K8S manifests that are being applied during refresh. In some charms (Seldon, Training Operator) we separated CRD and K8S resources deployment. And in some cases CRD must be installed before other manifests. In other charms CRDs and other manifests are applied in the by the same resource handler that does sorting of the resources before it applies them. To solve the issue, we either handle order in charm, or we revert to using single K8S handler to do ordering for us. I am leaning towards putting everything back into single handler. I need to confirm this first.
> 
> @i-chvets before changing anything, we need to understand what is the issue you are running into. Please modify the description of this issue with logs, error messages and steps to reproduce. You have referenced two different error messages and two different set of steps to reproduce, and that makes it hard to understand.

The error message that you see in local charm steps is the one that is buried deep in the framework. I just changed top level generic `K8S resources creation failed` message to actually report the error the framework gives us.

**Comment by i-chvets** [comment]
In previous `training-operator` charm (`1.5/stable`) resources were created without specifying `field_manager`. After the re-write with `chisme` and using server-side-apply method `field_manager` is a required parameter and is specified in our latest charm as `lightkube`. As a result, changes in CRD are not allowed, because `field_managers` are different: not-specified one in previous charm versus `lightkube` in latest charm.
Explanation of reason for the conflict: https://kubernetes.io/docs/reference/using-api/server-side-apply/

There is an option to do forced change. It will require charm code changes and `chisme` code changes.

**Comment by i-chvets** [comment]
Verified by this script `lightkube-client.py`
```
#!/usr/bin/python3

from lightkube import ApiError, Client, codecs
from lightkube.resources.apiextensions_v1 import CustomResourceDefinition

client = Client(field_manager="lightkube")

with open('crds_manifests.yaml') as f:
    for obj in codecs.load_all_yaml(f):
        try:
            res = client.apply(obj)
        except ApiError as err:
            print(f"Failed to apply {obj.metadata.name}")
            print("Apply with force='True'")
            res = client.apply(obj, force=True)
```
After deployment of `1.5/stable`:
```
$ kubectl get crds -l app.juju.is/created-by=training-operator -o=yaml | grep "ontroller-gen.kubebuilder.io/version"
      controller-gen.kubebuilder.io/version: v0.6.0
      controller-gen.kubebuilder.io/version: v0.6.0
      controller-gen.kubebuilder.io/version: v0.6.0
      controller-gen.kubebuilder.io/version: v0.6.0
      controller-gen.kubebuilder.io/version: v0.6.0
```

Use script above to update CRDs.
Result:
```
$ ./lightkube-client.py 
Failed to apply xgboostjobs.kubeflow.org
Apply with force='True'
Failed to apply tfjobs.kubeflow.org
Apply with force='True'
Failed to apply pytorchjobs.kubeflow.org
Apply with force='True'
Failed to apply mxjobs.kubeflow.org
Apply with force='True'
Failed to apply mpijobs.kubeflow.org
Apply with force='True'
$ kubectl get crds -l app.juju.is/created-by=training-operator -o=yaml | grep "ontroller-gen.kubebuilder.io/version"
      controller-gen.kubebuilder.io/version: v0.10.0
      controller-gen.kubebuilder.io/version: v0.10.0
      controller-gen.kubebuilder.io/version: v0.10.0
      controller-gen.kubebuilder.io/version: v0.10.0
      controller-gen.kubebuilder.io/version: v0.10.0
```

**Comment by i-chvets** [comment]
Need to address [this issue](https://github.com/canonical/charmed-kubeflow-chisme/issues/35) first.

**Comment by i-chvets** [comment]
Proposed fix:
- Update to chisme to expose `force` parameter in `apply()` function.
- Add `force` parameter when applying K8S resources in training operator.

**Comment by i-chvets** [comment]
Looks like it happens when pebble-ready event is handled. It cannot resolve and upgrade charm event handler never gets to run.
I will add troubleshooting section to upgrade guide on how to recover, but we need to look into it. I think, pebble ready event handler needs rework.

**Comment by i-chvets** [comment]
Fix has been merged.
